//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmortalVentureService.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HakatonModelContainer : DbContext
    {
        public HakatonModelContainer()
            : base("name=HakatonModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Пользователь> ПользовательSet { get; set; }
        public virtual DbSet<МедосмотрСВрачом> МедосмотрСВрачомSet { get; set; }
        public virtual DbSet<МедосмотрАвтоматический> МедосмотрАвтоматическийSet { get; set; }
        public virtual DbSet<Водитель> ВодительSet { get; set; }
        public virtual DbSet<Врач> ВрачSet { get; set; }
    }
}
