//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmortalVentureService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class МедосмотрАвтоматический
    {
        public int Id { get; set; }
        public System.DateTime Дата { get; set; }
        public Nullable<decimal> Температура { get; set; }
        public Nullable<int> ДавлениеВерхнее { get; set; }
        public Nullable<int> ДавлениеНижнее { get; set; }
        public Nullable<int> Пульс { get; set; }
        public Nullable<decimal> ОпьянениеПромилле { get; set; }
        public Заключение Заключение { get; set; }
        public string ВнешнийХэш { get; set; }
    
        public virtual Водитель Водитель { get; set; }
    }
}
