//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmortalVentureService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class МедосмотрСВрачом
    {
        public int Id { get; set; }
        public System.DateTime Дата { get; set; }
        public string Жалобы { get; set; }
        public string ВизуальныйОсмотр { get; set; }
        public decimal Температура { get; set; }
        public int ДавлениеВерхнее { get; set; }
        public int ДавлениеНижнее { get; set; }
        public int Пульс { get; set; }
        public decimal ОпьянениеПромилле { get; set; }
        public Заключение Заключение { get; set; }
        public string Комментарий { get; set; }
    
        public virtual Водитель Водитель { get; set; }
        public virtual Врач Врач { get; set; }
    }
}
